"""Add exercises to RuleExplanation

Revision ID: 070d1b2439e1
Revises: fc4e14ef998b
Create Date: 2026-05-22 22:22:38.520969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070d1b2439e1'
down_revision: Union[str, Sequence[str], None] = 'fc4e14ef998b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_explanations', sa.Column('exercises', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_explanations', 'exercises')
    # ### end Alembic commands ###
