"""Add display_title to RuleExplanation

Revision ID: 37c377404775
Revises: b3941c93212e
Create Date: 2026-05-21 18:17:50.227467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c377404775'
down_revision: Union[str, Sequence[str], None] = 'b3941c93212e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_explanations', sa.Column('display_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_explanations', 'display_title')
    # ### end Alembic commands ###
