"""Update progress table

Revision ID: 511468aab531
Revises: 0db9cf9c5b8f
Create Date: 2026-06-16 17:47:11.042428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '511468aab531'
down_revision: Union[str, Sequence[str], None] = '0db9cf9c5b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('next_review', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'next_review')
    # ### end Alembic commands ###
