"""Use MutableList for ChatSession history

Revision ID: 73d15ff53f13
Revises: ede8632e90c4
Create Date: 2026-06-04 18:00:15.898127

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '73d15ff53f13'
down_revision: Union[str, Sequence[str], None] = 'ede8632e90c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
