"""Revert UniqueConstraint for RuleExplanation to include level

Revision ID: b3941c93212e
Revises: fd92f5f8ea77
Create Date: 2026-05-11 19:38:03.000961

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b3941c93212e'
down_revision: Union[str, Sequence[str], None] = 'fd92f5f8ea77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_explanation_chunk_lang'), 'rule_explanations', type_='unique')
    op.create_unique_constraint('_chunk_level_lang_uc', 'rule_explanations', ['chunk_id', 'level', 'lang'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_chunk_level_lang_uc', 'rule_explanations', type_='unique')
    op.create_unique_constraint(op.f('uq_explanation_chunk_lang'), 'rule_explanations', ['chunk_id', 'lang'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
