"""Add RuleExplanation table

Revision ID: dedadb7bbab8
Revises: 808a104bb405
Create Date: 2026-05-07 18:07:33.467186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dedadb7bbab8'
down_revision: Union[str, Sequence[str], None] = '808a104bb405'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('lang', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chunk_id', 'level', 'lang', name='_chunk_level_lang_uc')
    )
    op.create_index(op.f('ix_rule_explanations_chunk_id'), 'rule_explanations', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_explanations_chunk_id'), table_name='rule_explanations')
    op.drop_table('rule_explanations')
    # ### end Alembic commands ###
