"""Add related_rules to RuleExplanation

Revision ID: fc4e14ef998b
Revises: 37c377404775
Create Date: 2026-05-22 16:45:29.664731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc4e14ef998b'
down_revision: Union[str, Sequence[str], None] = '37c377404775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_explanations', sa.Column('related_rules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_explanations', 'related_rules')
    # ### end Alembic commands ###
