"""Add RuleExplanation table

Revision ID: fd92f5f8ea77
Revises: dedadb7bbab8
Create Date: 2026-05-09 13:35:46.166845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd92f5f8ea77'
down_revision: Union[str, Sequence[str], None] = 'dedadb7bbab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_explanations', sa.Column('topic', sa.String(length=100), nullable=False))
    op.add_column('rule_explanations', sa.Column('subtopic', sa.String(length=100), nullable=False))
    op.alter_column('rule_explanations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('_chunk_level_lang_uc'), 'rule_explanations', type_='unique')
    op.create_unique_constraint('uq_explanation_chunk_lang', 'rule_explanations', ['chunk_id', 'lang'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_explanation_chunk_lang', 'rule_explanations', type_='unique')
    op.create_unique_constraint(op.f('_chunk_level_lang_uc'), 'rule_explanations', ['chunk_id', 'level', 'lang'], postgresql_nulls_not_distinct=False)
    op.alter_column('rule_explanations', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('rule_explanations', 'subtopic')
    op.drop_column('rule_explanations', 'topic')
    # ### end Alembic commands ###
